apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-scorecard-genxiii
  labels:
    app: risk-scorecard-genxiii
spec:
  #ensure 2 pods with HA so PodDisruptionBudget works properly
  replicas: {{ternary 2 1 .Values.enableHA}} 

  minReadySeconds: 3
  selector:
    matchLabels:
      app: risk-scorecard-genxiii
  template:
    metadata:
      labels:
        app: risk-scorecard-genxiii
    spec:
      automountServiceAccountToken: false
      containers:
      - name: risk-scorecard-genxiii
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http-port
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: {{ .Values.requestMemory }}
            cpu: {{ .Values.requestCpu }}
          limits:
            memory: {{ .Values.limitMemory }}
            cpu: {{ .Values.limitCpu }}
