SELECT
    ACCOUNTID,
    REQUEST_DATETIME,
    RESPONSE_MODEL_NAME,
    RESPONSE_MODEL_VERSION
FROM 
    RAW.SOURCE_S3_SCOREHISTORY.PAYLOAD_PARSED
WHERE RESPONSE_MODEL_NAME = 'PRESTIGE-DLV1'
ORDER BY REQUEST_DATETIME ASC